### ISSUE TITLE
Summary reports wrong payment amount in cash sales and wrong count in general sales

### ISSUE THREAD

**Issue by truchosky** [opensourcepos/opensourcepos#1972]
### Installation information

- OSPOS version is:  3.2.1
- OSPOS git commit hash is: 
- PHP version is:  7.0
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature
Hi guys, when you create a summary_sales report of total sales then the amount is correct. no problem there.
But if you create a report from summary_payments then the amount on cash sales is incorrect, and payment counts too not only in cash.

summary payment report in cash includes payment amounts with out discount the change (in cash sales), that is why cash summary payment amount is bigger than real

**Comment by odiea** [comment]
Upgrade to 3.2.0

**Comment by truchosky** [comment]
ok, I will and then report back

**Comment by truchosky** [comment]
it doesnt fix it, I have a lot of differents summaries, the correct one is in summary_sales.
Now in summary payments the count of each payment is wrong and the ammounts too
and daily sales is the same, incorrect data

data:
on summary payments
Version 3.1.1 total sales are 253, 143 cash, 24 credit card and 86 debit card, total ammount of 4.284.100, this is perfect.
Version 3.2.0 total sales are 240, 136 cash, 23 credit card and 81 debit card, total ammount of 4.284.100, total ammount is correct but there are missing 7 sales in cash, 1 sale in credit card and 5 sales in debit card.

on summary_sales both versions are correct

on daily sales both versions are incorrect, both shows 253 transactions but totals are incorrect, and when you move to the next page the cash ammount changes in each page, daily sales has a bigger ammount, 4.438.100, and it changes on each page of daily sales report

**Comment by daN4cat** [comment]
Hmmmm I thought I fixed it, let me test it again....

**Comment by daN4cat** [comment]
@truchosky I tested a couple of times and I can't reproduce this with 3.2.1.

Could you please try the demo server https://demo.opensourcepos.org/ and confirm you can reproduce it?
If yes, could you please explain in detail what you have done?
Because I deleted some sales and in the summary payment I see the correct number of payments as in details sales (where I don't see the deleted sales listed), in summary sale I see the same details as in detail sales (bear in mind the summary sale reports the total sales by each day so there are less than details).

**Comment by odiea** [comment]
@mckaygerhard Yes it is like windows. A full upgrade needs to be installed to get the benefits of the new 3.2.0.

**Comment by mckaygerhard** [comment]
@odiea that i refers its in other meaning.. mocosoft always said "upgrade (and piad in their case)" and THEN qhen upgrade "process" compelte the problem still are there

**Comment by mckaygerhard** [comment]
untill the commits of sales recently the problem was stil present in 3.2.0 oficial release! that0s why @odiea that i refers its in other meaning.. mocosoft always said "upgrade (and piad in their case)" and THEN qhen upgrade "process" compelte the problem still are there

**Comment by truchosky** [comment]
I think I Found 2 "problems",

1. to fix count I used left join, and force date in where clause,

select sales_payments.payment_type, COUNT(sales_payments.sale_id) AS 'count', SUM(sales_payments.payment_amount) AS payment_amount
from(ospos_sales_payments AS sales_payments)
join ospos_sales AS sales on sales.sale_id = sales_payments.sale_id
**left** join ospos_sales_items AS sales_items on sales_items.sale_id = sales_payments.sale_id AND sales_items.line = 1
where **date**(sales.sale_time) BETWEEN '2018-04-01' and '2018-04-30'
group by sales_payments.payment_type;

2. Summary payment amount is wrong because on sum it includes the payment amount, and not the "item cost", example: I have and item and it costs 10, if I sold this item in cash and amount tendered is  100 then payment_amount is 100 and not 10, then the sum has 90 more because it considers payment amount with out discount change due

**Comment by daN4cat** [comment]
1. Good catch, I didn't have the time today to look into this any further. But I like when people help in fixing issues.

2. Well it's payment summary whether it's tendered or due. So indeed that needs fixing.

Thanks for the help.

**Comment by daN4cat** [comment]
I was wondering, maybe would be good to show amount due, amount tendered and change due (diff between the two amounts).

**Comment by truchosky** [comment]
on sales_payments table ?

**Comment by daN4cat** [comment]
in the Sales payment report. By the way the report now is not correct because it was displaying Amount tendered, where now is Amount due.... I need to fix it now and show everything otherwise it gets very confusing!

**Comment by daN4cat** [comment]
Fixed the table header to be amount due

**Comment by odiea** [comment]
Current version current demo. Payments summary report is showing the subtotal of the sale not the full amount with taxes included.

**Comment by WebShells** [comment]
@odiea didnt get that... Total is subtotal + tax... whats wrong in the display :x ?

**Comment by odiea** [comment]
The table view is showing the amount due as 6.00 when it should be 6.44.

![2018-08-08 09_49_16-open source point of sale _ powered by ospos 3 3 0](https://user-images.githubusercontent.com/10962177/43848571-741cb71a-9af0-11e8-9e58-627bc59532ea.png)

**Comment by WebShells** [comment]
Excuse me was looking at transactions summary part... Maybe tax calculations are missing @daN4cat ?
as am checking the query:

SUM(sales_items.item_unit_price * sales_items.quantity_purchased * (1 - sales_items.discount_percent / 100) AS payment_amount

The item_unit_price doesn't include the tax calculation... I guess we should retrieve from sales_taxes and add it to the above summation...

**Comment by daN4cat** [comment]
Fixes are welcome!

**Comment by truchosky** [comment]
a "temporary" fix will work only if you use taxes in all your sales

**Comment by SteveIreland** [comment]
Thanks @truchosky for adding a comment on this so that it caught my attention.  Since I'm reworking the tax logic so I will be reviewing the issues here and including any needed fixes in the India GST project.

**Comment by SteveIreland** [comment]
On the payments summary don't we want to report the amount actually paid and not the amount the sale amount?  Just looking at the code I also noticed that the gift cards are computed using the actual paid amount and not the sale amount.  So something seems a bit out of sync.  I don't have time to explore it further but that's what I saw at first glance.

**Comment by SteveIreland** [comment]
I'm also assuming that the grand totals should reflect the sales total of all invoices that have had at least one payment.  

Should those sales that have not had a single payment also be included in the grand totals?

**Comment by SteveIreland** [comment]
I'm also assuming that the subtotal should have the taxes backed out in a "tax included" pricing situation. I don't see where that is taking place.

**Comment by SteveIreland** [comment]
There is a question or two here. Hopefully someone can provide some insight for me.

I'm going to alter the report to be the total of payments by payment type.  Does anyone have a problem with this proposal?  I was looking at the code and that doesn't seem to be the case.

The count is going to be the total number of payments using that payment type.

Also, the totals include a pretax subtotal, taxes, and total sales.

The question is should the totals include sales totals even for those that don't have any payments at all or should it be the sum of invoices that only?

Obviously if no one responds then I'll start making some assumptions.  I think that the totals should include invoice sales that have not received any payments at all.

**Comment by odiea** [comment]
If you can include Invoices as a payment type in the summary report then I would think it would be ok either way as long as they know the funds may not be in the till.

**Comment by SteveIreland** [comment]
So you are using the report as a reconciliation tool.   Then it seems it would be helpful to break out the totals by sales type.

**Comment by odiea** [comment]
With Invoices not being a normal payment type it would have to be displayed as a sale type.

**Comment by SteveIreland** [comment]
Just letting everyone know that I've started on a significantly improved variation of this report.  I have 2 "bugs" assigned to me and this is one of those two. The goal is to slip this in within the 3.3 release.

**Comment by jekkos** [comment]
@SteveIreland great, thanks for the bugfixing effort here. In terms of SQL aggregates, we should be careful not create any fanout in our queries. [Check this site](https://looker.com/blog/aggregate-functions-gone-bad-and-the-joins-who-made-them-that-way) for a nice readup.

**Comment by SteveIreland** [comment]
Okay. Thanks

**Comment by SteveIreland** [comment]
A pull request has been submitted for feedback.

#2391

**Comment by SteveIreland** [comment]
Below is what the new report generally looks like.

![image](https://user-images.githubusercontent.com/23066623/53704816-e16be980-3ded-11e9-8586-12b81cf33849.png)

**Comment by SteveIreland** [comment]
@odiea @truchosky 

Any feedback for me?

**Comment by odiea** [comment]
Not yet. Grand daughter has been on my computer most of the day. Will check later.

**Comment by truchosky** [comment]
At the moment, all good, even with taxes

**Comment by odiea** [comment]
Looks good but I was expecting to see the sale amount Under the transactions amount column across from payments

**Comment by SteveIreland** [comment]
Okay, I was expecting that.  :-)  So let's discuss the possible options that I see and I'm open to other options (if they are possible).

Assume I have a sale for $10  and the customer pays $6 with a gift card and hands me a $20 bill for the balance.  That means I have to refund $16 dollars.  So this involves the following transactions.  (Refund is not stored as a database transaction and as such is a derived amount.)

| Transaction | Amount |
| :--- | ---: |
| Sale | $10 |
| Gift Card | $6 |
| Cash |$20 | 
| Refund | $16 |

So if I simply list the payments with the sale amount associated with the payment on the same line as each payment type then that seems to be misleading to me.  But maybe it is what is needed?

| Transaction | Amount | Sale | Refund |
| :--- | :---: | :---: | ---: |
| Sale | $10 | $10 | -$16 | 
| Gift Card | -$6 | $10 | |
| Cash |-$20 | $10 | |

The following is something I considered.  It's a bit more complex but if I add up the columns then they balance to zero.  Of course, refund isn't logged as a payment type.  It's more a balancing amount to bring a POS transaction to net zero and would need to be added to a fabricated row.  For invoices there is the balance Due that would also need to be added as a fabricated row.

For the following table the portion of the sale amount that is covered by the payment is listed.

| Transaction | Amount | Sale |
| :--- | :---: | ---: |
| Sale | $10 | | 
| Gift Card | -$6 | $6 |
| Cash |-$20 | $20 |
| Refund | $16 | -$16 | 

Which of these comes closest to what you need?  Is there another variation that  better serves your needs?

**Comment by SteveIreland** [comment]
@truchosky Do you use internal or external tax?  If internal then it looks like I have a bug because for internal tax scenario taxes should not be being added to the sale amount.  I'll try to fix that tomorrow night.

**Comment by odiea** [comment]
@SteveIreland  What I had to do to get the correct totals for cashups was to add a column to sales_payments called total_amount and extract the info from that. By no means am I a programmer..LOL

**Comment by SteveIreland** [comment]
Updated the pull request to fix the the bug with internal tax environment.  I also made an attempt to associate the refund identified in the sale group with the cash payment type and adjusted the cash payments accordingly.

This change assumes, of course, that all refunds are cash refunds.  Maybe a future change will store the type of refund.

**Comment by SteveIreland** [comment]
@odiea What was in the column you added for total_amount?  With this last change I am using the column labeled payments as a net total payments (payment transaction - refunded).  The total payment amount is now in the transaction amount column in the payments section.

**Comment by odiea** [comment]
Great. In the total amount column I put the Sale total into it. I could not find a way in Cashups to get the change due to subtract it from the cash sale.

**Comment by truchosky** [comment]
sorry the late, yes, it was tested as internal tax

**Comment by odiea** [comment]
Here is what the payments table looks like.
![2019-03-06 08_13_04-window](https://user-images.githubusercontent.com/10962177/53891554-de3c4d80-3fe7-11e9-9b3e-3e7c9c44090d.png)

**Comment by SteveIreland** [comment]
Oh, so you have added a local customization that tracks the amount actually paid?

That's what I'm attempting to do with the report, so theoretically we should have the same totals.

**Comment by odiea** [comment]
Yes Takings also does show the  total amount in cash and I believe the structure to do that might be in tabular_helper.

**Comment by odiea** [comment]
I don't know if this will help you out.
```
function get_sales_manage_payments_summary($payments, $sales)
{
	$CI =& get_instance();
	$table = '<div id="report_summary">';
	foreach($payments as $key=>$payment)
	{
		$amount = $payment['payment_amount'];
		// WARNING: the strong assumption here is that if a change is due it was a cash transaction always
		// therefore we remove from the total cash amount any change due
		if( $payment['payment_type'] == $CI->lang->line('sales_cash') )
		{
			foreach($sales->result_array() as $key=>$sale)
			{
				$amount -= $sale['change_due'];
			}
		}
		$table .= '<div class="summary_row">' . $payment['payment_type'] . ': ' . to_currency($amount) . '</div>';
	}
	$table .= '</div>';
	return $table;
}
```

**Comment by SteveIreland** [comment]
That's exactly what I'm doing.

**Comment by odiea** [comment]
My question is which one is more inefficient. Writing code to create something that is not there or storing the total in a new column sales_payments?

**Comment by odiea** [comment]
@SteveIreland Are the transactions under payments  reversed?
![2019-03-07 04_36_21-window](https://user-images.githubusercontent.com/10962177/53954231-dab1d080-4092-11e9-83ec-edeee34f467b.png)

**Comment by odiea** [comment]
@SteveIreland Thanks for this new report. I was able to incorporate it into Cashups and now I can get rid of the way I was doing it. The only issue I see in my master was the reversed payments as shown above.

**Comment by SteveIreland** [comment]
Sorry for the delayed response.  My wife wouldn't bring my laptop to the hospital.

In the transaction column it seemed to make sense to me to have sales as positive amounts and sales as negative.  However if you need them all as positive I'll be happy make that small correction.

**Comment by odiea** [comment]
Sorry you are in the Hospital. Get better soon. I don't mind the minus sign but to me it appears after the Sales row that the transaction amount and payments appear to be reversed. Shouldn't the payment  be higher then the Transaction amount. This only shows on cash sales with change due.

**Comment by odiea** [comment]
Maybe I am seeing it wrong.

**Comment by SteveIreland** [comment]
Nope, I can see your perspective.  I was defining the transaction amount as the original transaction but I believe your perspective makes more sense

**Comment by SteveIreland** [comment]
I'm out of the hospital now which is why I have access to my computer again.

**Comment by odiea** [comment]
I just reversed the 2 and I was happy.

**Comment by SteveIreland** [comment]
I did too, but also fixed a problem with the gift card collapse logic  These changes are in master now.

**Comment by daN4cat** [comment]
@odiea what's the change in cash ups that you made?

**Comment by daN4cat** [comment]
@SteveIreland get a rest. Hope you didn't attempt to break your neck again...

**Comment by odiea** [comment]
![2019-03-10 05_25_27-Window](https://user-images.githubusercontent.com/10962177/54084374-66c33280-42f5-11e9-81d0-d7459033e333.png)

**Comment by odiea** [comment]
The in out cash is now readonly and taken from the day close in the till.
Inputs on the right are only viewed if you have access to the config setup.
Inputs on right are auto filled out with the summary report form depending on what changes @SteveIreland  makes so the cash portion is from the Sale total and not the payment amount.
As per my lack of trust the employee has to enter the cash in the till.
```
// get all the transactions payment summaries
			$this->load->model('reports/Summary_payments');
			$reports_data = $this->Summary_payments->getData($inputs);		
					
			foreach($reports_data as $row)
			{
				if($row['trans_type'] == $this->lang->line('sales_cash'))
				{					
					$cash_ups_info->expected_closed_amount_cash += $this->xss_clean($row['trans_amount']);
				}
				elseif($row['trans_type'] == $this->lang->line('sales_due'))
				{
					$cash_ups_info->closed_amount_due += $this->xss_clean($row['trans_amount']);
					$cash_ups_info->expected_closed_amount_due += $this->xss_clean($row['trans_amount']);
				}
				elseif($row['trans_type'] == $this->lang->line('sales_debit') || 
						$row['trans_type'] == $this->lang->line('sales_credit'))
				{					
					$cash_ups_info->closed_amount_card -= $this->xss_clean($row['trans_amount']);
					$cash_ups_info->expected_closed_amount_card -= $this->xss_clean($row['trans_amount']);
				}
				elseif($row['trans_type'] == $this->lang->line('sales_check'))
				{
					//$cash_ups_info->closed_amount_check += $this->xss_clean($row['payment_amount']);
					$cash_ups_info->expected_closed_amount_check -= $this->xss_clean($row['trans_amount']);
				}
			}
```

**Comment by odiea** [comment]
The in out cash must be recorded in Expenses for a better audit trail

**Comment by odiea** [comment]
I am also finding out now if the Date Time filter is used then multiple Cashups can be performed after submitting the form and it won't bring in the previous times totals.

**Comment by SteveIreland** [comment]
@daN4cat Nope, it wasn't stupidity this time.   It was genetics.   Had a little stroke but I'm back, thankfully with very little damage.

This ticket originally wasn't about cashups (so I thought) but I like where this is heading.

I haven't done any work on the cashups yet and would like to learn a bit more about the workflow involved.  So I'm volunteering to incorporate the changes by @odiea

**Comment by daN4cat** [comment]
@SteveIreland sorry to hear that. Please take it easy and have some rest, a stroke is not like having a flu.

**Comment by odiea** [comment]
@daN4cat and @SteveIreland  Should I include Gift Card payments in this form. After I hear back I will delete the cashups comments from this issue.

**Comment by SteveIreland** [comment]
@odiea I can drop the sales transactions from the output If that works better for you. 

I also see that you are combining credits and debit card payments into a single category which is needed for cashups.  It seems like including gift cards would be a necessity for those that issue them.

I believe it would be very helpful to write to the sales_payments table the refund amount and the amount due at the point of completion of the sale so that we don't need to calculate it and reporting would be greatly simplified.

What do you think about that?

**Comment by odiea** [comment]
I can drop the sales transactions from the output If that works better for you. I take it you mean the amount paid and not the amount due?
I have always thought it would be simpler to include those amounts into sales payments. The only real issue I had was when you tries to change the Payment type in sales edit.
Right now it is working good in your new report I just have to find which trans has the total sale amount.

**Comment by odiea** [comment]
I do not know if adding more columns to the cashup table would really effect anything. Currently I have increased the amount by 5.

**Comment by SteveIreland** [comment]
The payments report array now consists of three group types ("trans_group").  "Sales", "<HR>",  and "Payments".

Technically the values are
* $this->lang->line('reports_trans_sales')
* "<HR">
* $this->lang->line('reports_trans_payments')

You only want the "Payment", a.k.a. $this->lang->line('reports_trans_payments'),  and the amount that I believe you want is now in "trans_amount" which is "trans_payments - refunds"

**Comment by odiea** [comment]
Thanks. That was the one I chose. I just add Gift Cards to cash ups also.

**Comment by SteveIreland** [comment]
So is this complete or do I need to tweak it a bit for you?

**Comment by odiea** [comment]
@SteveIreland If you are talking to me it has been working great thanks.

**Comment by odiea** [comment]
I am having 1 minor issue. The giftcard field works fine if a giftcard is present if there is no giftcard it does show a different number. Your reports always shows correctly. Here is the code I am using to show the gift card value. I had to put float in front of it or there were complains about not being a numeric valve later when the ammount was added to the total. If you have any ideas please let me know. Thanks Odiea

```
elseif($row['trans_type'] == $this->lang->line('sales_giftcard'));
				{
					$cash_ups_info->closed_amount_giftcard = (float)$this->xss_clean($row['trans_amount']);
					$cash_ups_info->expected_closed_amount_giftcard = (float)$this->xss_clean($row['trans_amount']);
				}

**Comment by SteveIreland** [comment]
@odiea I don't have time tonight to explore this in depth, but trans_amount is numeric, however passing it through xss_clean is going to change it to a string value and possibly do other unnatural things to it.  I don't believe it is necessary to apply xss_clean to the amount because it is a calculated numeric value.

**Comment by odiea** [comment]
No problem. It's just a little quirky.

**Comment by odiea** [comment]
@SteveIreland . Do not waste your time on looking for this issue. It may be something with my Cashups controller. But the current cashups controller needs to be changed to your new trans_type and trans_amount

**Comment by SteveIreland** [comment]
Thanks for letting me know.  I didn't know we had any code reuse like that going on.

**Comment by odiea** [comment]
Yes. That's why I was glad to see your updated cash instead of amount paid. Makes the register or Cashup show the correct cash in the Till

**Comment by daN4cat** [comment]
@odiea are we happy with cashup or more needs to be done?

**Comment by odiea** [comment]
@daN4cat  I think the current cashup should be fine now.

**Comment by odiea** [comment]
There has not been much feed back on this until recently. So the only suggestions I could make would be to read only the in/out field and in cashups controller change line 143 to transfer amount and make them use the expense module for cash withdrawals and have that taken out of the closed cash amount.
