### ISSUE TITLE
Docker install not functioning on my systems

### ISSUE THREAD

**Issue by darkjedeye** [opensourcepos/opensourcepos#3164]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation and modified according to install instructions
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: latest and 3.3.2
- OSPOS git commit hash is: not sure
- PHP version is: 7.4 but not relevant as it's your docker
- MySQL or MariaDB version is: your docker
- OS and version is: both Linux mint 20 and ubuntu xenial 64 vagrant
- WebServer is: your docker Nginx
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

I have followed your docker installation a few times on my mint 30.04 laptop and a vagrant box on the same machine. in all instances, after completed i have no access to the system via any associated ip, localhost or docker ip. when i monitor the dockers on the vagrant box, nginx and mariadb containers di as soon as you try and access the system. On the mint laptop, all still runs but I get no site.... not even 404 error, which leads me to belive it is a networking issue docker side... i am using the latest docker from get.dock.com, if I set it to host network, I get connection refused.

I have run the system straight from install without any edits for testing with docker-compose up, with docker-compose up -d and same commands via tmux i have even tried with editing network to host and even with editing the usernames and passwords for the env factors for the YAML file... and to no avail... I am trying to find out if it is a problem with my system installs or something else.

I am more than willing to give you ssh access to the vagrant box, that's fairly easy.... depending on the network traffic

**Comment by kumaranar** [comment]
I faced similar issue with chrome (blank page not even a 404) but when i used firefox it worked like a charm. One more common mistake is to try running in from a clone of the master branch. Did you download the latest release or cloned the master branch?

**Comment by darkjedeye** [comment]
> I faced similar issue with chrome (blank page not even a 404) but when i used firefox it worked like a charm. One more common mistake is to try running in from a clone of the master branch. Did you download the latest release or cloned the master branch?

downloaded the master and used latest release

**Comment by darkjedeye** [comment]
just tried again with fresh docker install following the instructions from the docker install wiki and noticed that the Nginx and MariaDB containers continuously restart.

**Comment by darkjedeye** [comment]
on further inspection, with some knowledge of docker, your readme and wiki need some development instructing the user who has no docker knowledge, as to what to change in the docker-compose.yml will assist on that as soon as I figure it out

**Comment by darkjedeye** [comment]
What am I supposed to set the ospos_ci_env to?

**Comment by jekkos** [comment]
The docker setup was reworked not so long ago. You report that you tried 3.3.2. Can you remove all containers and just run

`docker-compose up` in the project folder?

**Comment by jekkos** [comment]
The problem is that the port is not exposed to the host by default. You need to run it as follows

`docker-compose -p80:80 up`

I'll adapt the compose file so that it exposes by default.

**Comment by darkjedeye** [comment]
Thanks so much.


Regards,
Eric Klein
0714671302

**Comment by jekkos** [comment]
Can you try the regulation docker-compose.yml? It should not have nginx

**Comment by darkjedeye** [comment]
Hi there, deleted everything and followed instruction to the T except one step, as it fails each time.

Local Docker install
Terminal windows must be open: in MacOSX at Finder->Accesories->Terminal in Linux at Menu->SystemTools->Terminal, then a window with prompt will show, in Linux flavors must gain root access only for next step with sudo su command

Dependences install: docker.io, please refer to the docker documentation for better instructions: in MAC all included in docker.img file by launching it, drag Moby the whale to the Applications folder and later relaunch service from Finder, in Linux for Deb and RPM based distribution are apt-get install docker.io or/and yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo;yum install -y docker-ce respectively, oldstable deb distributions may need "backports" or "external" repositories. After install hit "CRTL+D" to out from root account.

Dockerplace working directory for the dockerfile of ospos: this it's change the working directory in the current terminal window, assuming the ~ represent your home with a docker root document directory and you can move to by executing mkdir ~/osposdocker;cd ~/osposdocker but remenber this depends of the Operating System Docker install too.

Download Retrieve a prebuilt version of OSPOS using the latest release. Execute in same terminal: wget https://github.com/opensourcepos/opensourcepos/releases/download/3.3.2/opensourcepos.20200903075833.3.3.2.bb309c.zip -O osposlastedstable.zip to later move to the htdoc directory.

Uncompress to htdocs the download: tar zxvf osposlastedstable.tar.gz --strip 1 -C ~/osposdocker this will populate all the docker root image directory only for the software. **This step fails on a zip file**

Build+Run the image with following commands docker-compose build and then later docker-compose up, take in consideration password administrative privileges for the database users.


And still end up with nginx

**Comment by darkjedeye** [comment]
Docker-compose file in 3.3.2 has Nginx config. starts at line 71... which version should I try?

**Comment by jekkos** [comment]
Can you try the compose file from 3.3.4?

**Comment by jekkos** [comment]
Ok I see I'll update the link  in the wiki.

**Comment by darkjedeye** [comment]
> Can you try the compose file from 3.3.4?

Didn't even know that was out yet... please email me link eric@kleincore.co.za would like to help where i can

**Comment by jekkos** [comment]
https://github.com/opensourcepos/opensourcepos/releases/tag/3.3.4

**Comment by darkjedeye** [comment]
no joy on that either.... still no page displayed
I have tried with both docker-compose up and docker-compose -p80:80 up with no page being displayed... i will try on a VM and see as well

**Comment by jekkos** [comment]
Are you on linux? Can you check the permissions on database/database.sql?
Do a 

`chmod 664 database/database.sql`

then restart the docker-compose

**Comment by jekkos** [comment]
It seems that https was still set to force=true, I have done a fix for this.

**Comment by darkjedeye** [comment]
Having a look now, sorry, just woke up... I had a look at the docker-compose.yml file very clean and concise... and i did notice the change in the force HTTPS will keep you posted, and yes I do use Linux.

**Comment by darkjedeye** [comment]
WHOO HOO! getting into territory I can understand now.... getting this error 'Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php' Baring in mind, I have just pulled this to a directory for testing to get something working.... going to have a look at it and see.. possible that it is a config error somewhere. I may have done it on my side, not sure. but at least now there is a response!!!!! you are epic.

**Comment by jekkos** [comment]
Ok I think I pushed a wrong image yesterday for 3.3.4. I'll update it with tag so you'll have to remove it once and pull it in again

**Comment by jekkos** [comment]
This is also the reason our demo server is down now.

**Comment by jekkos** [comment]
Ok demo is back up, can you pull in again the docker image ? 

just remove the old one first `docker image rm jekkos/opensourcepos:3.3.4`

**Comment by darkjedeye** [comment]
I know this issue is closed, still not able to access my side when docker containers are running, so going to revert back to manual install

**Comment by jekkos** [comment]
I hope you're in good health now.

Did you try to remove the 3.3.4 image before running the docker again?

**Comment by darkjedeye** [comment]
> I hope you're in good health now.
> 
> Did you try to remove the 3.3.4 image before running the docker again?

I am much better. Thank you. The meds have worked. And I removed all images, all containers, the whole git repo download. Restarted and started from download again. Head over to the ip of the machine and get a 500 error. Head over to local host on the machine, 500 error. With connection refusal. So might be my system, might be my lack of knowledge with docker... Not sure either way.

**Comment by jekkos** [comment]
you did try the 3.3.4 right?

**Comment by jekkos** [comment]
Ok I'm quite surprised and would like to know what is causing this. So you have started the 3.3.4 docker-compose.yml from the project root right?
It does work on demo currently so not sure why it would be broken like this.

**Comment by darkjedeye** [comment]
if you can give me a timezone you are in, we can arrange a time and I will give you ssh access to the machine to have a look?

**Comment by jekkos** [comment]
Ok that would be good. I'm in UTC+1 at this moment. DST does apply so in practice its UTC+2.

What time would suit you? Maybe somewhere tonight at 22pm UTC+2?

**Comment by darkjedeye** [comment]
Hey there, sorry passed out early last night, you seem to be +-2hrs behind me, I am in johannesburg South Africa. Can arrange during the course of today maybe. If you prefer live chat, send me a direct email if you prefer WhatsApp, or I will send you my discord when in my office a bit later.

**Comment by darkjedeye** [comment]
hey man, my discord is darkjedeye#9191 unless you have another way you would like to communicate...

**Comment by jekkos** [comment]
Ok might reach out tonight.

**Comment by jekkos** [comment]
I'm closing this one as it must be a local issue (currently the compose image is working on demo).
